export const upgradeList: UpgradeType[] = [
  {
    id: "1",
    name: "Lower AP Physics Pass Rate",
    icon: "icon1.png",
    cost: 10,
    costList: [10, 20, 30, 40, 50],
    perSecondIncrease: 0.5,
    description: "The class with the lowest overall pass rate of any AP exam is getting worse...",
  },
  {
    id: "2",
    name: "Make AP Spanish Language Audio Quieter",
    icon: "icon2.png",
    cost: 20,
    perSecondIncrease: 1.0,
    description: "Because who needs to hear the audio clearly during the exam? Not you.",
  },
  {
    id: "3",
    name: "Cut Exam Time for AP Computer Science A",
    icon: "icon3.png",
    cost: 30,
    perSecondIncrease: 1.5,
    description: "Less time to code, more time to panic. The exam just got shorter.",
  },
  {
    id: "4",
    name: "Make AP Biology Exam Date Sooner",
    icon: "icon4.png",
    cost: 40,
    perSecondIncrease: 2.0,
    description: "Surprise! The AP Bio exam is now even earlier in the year.",
  },
  {
    id: "5",
    name: "Add More Content to AP U.S. History",
    icon: "icon5.png",
    cost: 50,
    perSecondIncrease: 2.5,
    description: "Because 500 years of history wasn't enough, here's more to memorize.",
  },
  {
    id: "6",
    name: "Ban College Credit for AP Precalculus",
    icon: "icon6.png",
    cost: 60,
    perSecondIncrease: 3.0,
    description: "No more college credit for AP Precalculus. Sorry, students.",
  },
];
