export const upgradeList: UpgradeType[] = [
  {
    id: "upgrade-physics",
    name: "Lower AP Physics Pass Rate",
    icon: "icon1.png",
    cost: 10,
    // costList: [500, 1500, 3000, 6000, 12000],
    perSecondIncrease: 0.1,
    description: "The class with the lowest overall pass rate of any AP exam is getting worse...",
  },
  {
    id: "upgrade-ap-spanish",
    name: "Make AP Spanish Language Audio Quieter",
    icon: "icon2.png",
    cost: 50,
    perSecondIncrease: 0.3,
    description: "Because who needs to hear the audio clearly during the exam? Not you.",
  },
  {
    id: "upgrade-ap-compscia",
    name: "Cut Exam Time for AP Computer Science A",
    icon: "icon3.png",
    cost: 100,
    perSecondIncrease: 0.6,
    description: "Less time to code, more time to panic. The exam just got shorter.",
  },
  {
    id: "upgrade-ap-bio",
    name: "Make AP Biology Exam Date Sooner",
    icon: "icon4.png",
    cost: 500,
    perSecondIncrease: 2.0,
    description: "Surprise! The AP Bio exam is now even earlier in the year.",
  },
  {
    id: "upgrade-ap-us-history",
    name: "Add More Content to AP U.S. History",
    icon: "icon5.png",
    cost: 1000,
    perSecondIncrease: 2.5,
    description: "Because 500 years of history wasn't enough, here's more to memorize.",
  },
  {
    id: "upgrade-ap-precalc",
    name: "Ban College Credit for AP Precalculus",
    icon: "icon6.png",
    cost: 5000,
    perSecondIncrease: 3.0,
    description: "No more college credit for AP Precalculus. Sorry, students.",
  },
];
